CREATE TABLE payments
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id       UUID                                    NOT NULL,
    transaction_id VARCHAR(255),
    status         VARCHAR(255),
    amount         DECIMAL,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_payments PRIMARY KEY (id)
);

ALTER TABLE payments
    ADD CONSTRAINT uc_payments_orderid UNIQUE (order_id);